CREATE TABLE postgres.public.costumer (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	birthday DATE NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	phone VARCHAR(13)
)